import asyncio
import os
import shutil
from loguru import logger
from pathlib import Path
from typing import List, Dict, Any
from Backend.app.db.db import insert_chunks 

from Backend.app.core.repo_ingestion.ingest import clone_repo, get_all_files, process_metta_files # Assuming ingest.py contains these
from Backend.app.core.repo_ingestion.ingest import TEMP_DIR, DATA_DIR # Assuming config is imported here


# CONFIGURATION 
REPO_URL = "https://github.com/iCog-Labs-Dev/metta-moses" 
PROJECT_NAME = "metta-moses"


async def ingest_pipeline_to_db(repo_url: str) -> None:
    """
    Executes the full ingestion pipeline: clone, process, and insert into DB.
    """
    logger.info(f"Starting ingestion for repository: {repo_url}")
    repo_path: str = ""
    
    try:
        # 1. EXTRACT: Clone the repository
        repo_path = clone_repo(repo_url, TEMP_DIR)
        logger.info(f"Repository cloned to {repo_path}")
        
        # 2. TRANSFORM: Process files and get chunk data
        files: List[str] = get_all_files(repo_path)
        logger.info(f"Found {len(files)} files to process.")
        
        chunks_data: List[Dict[str, Any]] = process_metta_files(
            files, 
            DATA_DIR, 
            repo_root=repo_path,
        )

        if not chunks_data:
            logger.warning("No new chunks were generated by the processing function.")
            return

        # 3. LOAD: Insert the chunks into MongoDB
        logger.info(f"Attempting to insert {len(chunks_data)} chunks into MongoDB.")
        inserted_ids = await insert_chunks(chunks_data)
        
        logger.success(f"Successfully inserted {len(inserted_ids)} new chunks into MongoDB.")
        
    except Exception as e:
        logger.error(f"Ingestion failed due to an error: {e}")
        
    finally:
        # Cleanup the temporary clone directory
        if repo_path and os.path.exists(repo_path):
            logger.info(f"Cleaning up temporary directory {repo_path}")
            shutil.rmtree(repo_path, ignore_errors=True)
            
async def main():
    await ingest_pipeline_to_db(REPO_URL)

if __name__ == "__main__":
    asyncio.run(main())