version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - mongo
    env_file:
      - .env

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  qdrant_storage:
  mongo_data:
